- name: deploy zabbix agent and configuration
  hosts: all
  tasks:
    - name: add repo zabbix
      dnf:
        name: https://repo.zabbix.com/zabbix/7.2/release/rhel/9/noarch/zabbix-release-latest-7.2.el9.noarch.rpm
        disable_gpg_check: true
        state: present

    - name: install zabbix-agent
      dnf:
        name: zabbix-agent
        state: present

    - name: make sure zabbix-agent running and enable
      service:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: change target server zabbix
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server }}"
        state: present

    - name: change target server active zabbix
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server }}"
        state: present

    - name: change hostname zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname= {{ agent_hostname }}"
        state: present

    - name: config Metadata
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^HostMetadata='
        line: "HostMetadata=linux"
        state: present

    - name: restart zabbix agent after configuration
      service:
        name: zabbix-agent
        state: restarted
